apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phpmyadmin
    cluster: test1
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        name: phpmyadmin
        env:
        - name: PMA_HOST
          value: mysql-svc
        - name: PMA_PORT
          value: "3306"
        - name: PMA_USER
          value: admin
        - name: PMA_PASSWORD
          value: admin
        - name: PMA_ARBITRARY
          value: "1"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  labels:
    app: phpmyadmin
    tier: debug
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30056
